#!/usr/bin/env bash
# Prepare a rented Ubuntu 24.04 NVIDIA box for the native CUDA backend work
#
# Run from a synced speakrs tree: `bash scripts/cuda/setup-gpu-box.sh`
# The script is idempotent: every step checks its own result and skips work that
# is already done. It installs only public packages and downloads public models
# anonymously, so it needs and stores no credentials
#
# Layout it produces:
#   /workspace/env.sh      source it before building (rustup, cargo, CUDA 13, LLVM)
#   /workspace/rustup      RUSTUP_HOME (stable for speakrs, the cuda-oxide nightly)
#   /workspace/cargo       CARGO_HOME (cargo-oxide and its codegen backend)
#   /workspace/models      public CUDA-mode ONNX models, PLDA and metadata files
#   /workspace/ref         reference tensors and weights (filled by the references task)
#   /workspace/gpu-bench.lock  flock target for every timing or benchmark run
#
# The preinstalled CUDA 12.8 toolkit and cuDNN 9 stay the default `/usr/local/cuda`;
# CUDA 13 lives beside it and is only used to build kernels with cuda-oxide
set -euo pipefail

# --- pins -----------------------------------------------------------------------
# cuda-oxide `main`, resolved on 2026-10-02; its rust-toolchain.toml selects the nightly
CUDA_OXIDE_REV="918bbde123671153b29a89542f1781f1c7494c14"
CUDA_OXIDE_NIGHTLY="nightly-2026-08-28"
# cuda-oxide needs LLVM 21+ for `llc` and clang's resource headers for bindgen
LLVM_MAJOR="21"
# the box driver (580.x) supports at most CUDA 13.0; cuda-oxide needs a 13.x toolkit,
# and keeping it at the driver's version means no tool on the box is newer than what
# the driver can JIT
CUDA13_DASHED="13-0"
CUDA13_DOTTED="13.0"
CUDA12_DOTTED="12.8"

WORKSPACE="/workspace"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

log() { printf '\n==> %s\n' "$*"; }

# --- apt packages -----------------------------------------------------------------
apt_install_missing() {
    local missing=()
    local pkg
    for pkg in "$@"; do
        dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "install ok installed" ||
            missing+=("$pkg")
    done

    if [[ ${#missing[@]} -eq 0 ]]; then
        return
    fi

    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}"
}

log "base packages"
apt-get update -qq
apt_install_missing ca-certificates curl gnupg git build-essential pkg-config libssl-dev \
    jq rsync util-linux

log "LLVM/Clang ${LLVM_MAJOR} from apt.llvm.org"
LLVM_KEYRING="/usr/share/keyrings/apt.llvm.org.gpg"
LLVM_LIST="/etc/apt/sources.list.d/llvm-${LLVM_MAJOR}.list"
if [[ ! -f "$LLVM_KEYRING" ]]; then
    curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o "$LLVM_KEYRING"
fi

if [[ ! -f "$LLVM_LIST" ]]; then
    codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
    echo "deb [signed-by=${LLVM_KEYRING}] https://apt.llvm.org/${codename}/ llvm-toolchain-${codename}-${LLVM_MAJOR} main" >"$LLVM_LIST"
    apt-get update -qq
fi
apt_install_missing "llvm-${LLVM_MAJOR}" "clang-${LLVM_MAJOR}" "libclang1-${LLVM_MAJOR}"

log "CUDA ${CUDA13_DOTTED} compiler components (NVIDIA apt repo)"
# nvcc pulls cudart-dev (cuda.h), libnvvm (libdevice) and crt; nvJitLink and the
# cuRAND headers are what `cargo oxide doctor` and the host bindings also check
apt_install_missing "cuda-nvcc-${CUDA13_DASHED}" "libnvvm-${CUDA13_DASHED}" \
    "libnvjitlink-dev-${CUDA13_DASHED}" "libcurand-dev-${CUDA13_DASHED}"

# installing CUDA 13 packages can re-point the `cuda` alternative; keep 12.8 as the
# default runtime because cuBLAS 12 and cuDNN 9 for CUDA 12 are what the ORT path loads
for alt in cuda cuda-12; do
    if update-alternatives --list "$alt" 2>/dev/null | grep -q "/usr/local/cuda-${CUDA12_DOTTED}$"; then
        update-alternatives --set "$alt" "/usr/local/cuda-${CUDA12_DOTTED}" >/dev/null
    fi
done
# the CUDA 13 packages refreshed the loader cache while /usr/local/cuda pointed at 13.0,
# which drops cuBLAS 12 from it; rebuild the cache for the restored link
ldconfig

# the libcurand static archives are only needed to link cuRAND statically, which nothing
# here does; drop them to save disk
rm -f "/usr/local/cuda-${CUDA13_DOTTED}"/targets/x86_64-linux/lib/libcurand_static.a

# --- workspace layout -------------------------------------------------------------
log "workspace layout"
mkdir -p "$WORKSPACE/rustup" "$WORKSPACE/cargo" "$WORKSPACE/models" "$WORKSPACE/ref"
touch "$WORKSPACE/gpu-bench.lock"

cat >"$WORKSPACE/env.sh" <<EOF
# generated by scripts/cuda/setup-gpu-box.sh; source before building speakrs or kernels
export RUSTUP_HOME=${WORKSPACE}/rustup
export CARGO_HOME=${WORKSPACE}/cargo
export CUDA13_HOME=/usr/local/cuda-${CUDA13_DOTTED}
export CUDA_OXIDE_NIGHTLY=${CUDA_OXIDE_NIGHTLY}
# cuda-oxide reads CUDA_TOOLKIT_PATH first, so kernels build against CUDA 13 while
# CUDA_HOME and /usr/local/cuda keep pointing at the 12.8 runtime
export CUDA_TOOLKIT_PATH=\${CUDA13_HOME}
export CUDA_OXIDE_LLC=/usr/bin/llc-${LLVM_MAJOR}
export LIBCLANG_PATH=/usr/lib/llvm-${LLVM_MAJOR}/lib
# CUDA 13 tools first so cuda-oxide never picks the 12.8 nvcc; the 12.8 runtime libraries
# still come from the loader path, which this does not change
export PATH=\${CARGO_HOME}/bin:\${CUDA13_HOME}/bin:/usr/lib/llvm-${LLVM_MAJOR}/bin:\${PATH}
# the disk is small, so skip debug info in dev and test builds
export CARGO_PROFILE_DEV_DEBUG=0
export CARGO_PROFILE_TEST_DEBUG=0
export SPEAKRS_CUDA_MODELS=${WORKSPACE}/models
# the CUDA modes' safetensors weights, exported on the Mac with
# `scripts/cuda/export_weights.py --runtime-assets` and synced here; tests/cuda_pipeline.rs
# reads them
export SPEAKRS_CUDA_ASSETS=${WORKSPACE}/models-native
EOF

# shellcheck source=/dev/null
source "$WORKSPACE/env.sh"

# --- rust -------------------------------------------------------------------------
log "rustup with stable and ${CUDA_OXIDE_NIGHTLY}"
if [[ ! -x "$CARGO_HOME/bin/rustup" ]]; then
    curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs |
        sh -s -- -y --no-modify-path --profile minimal --default-toolchain stable
fi
rustup toolchain install stable --profile minimal --component rustfmt,clippy
rustup toolchain install "$CUDA_OXIDE_NIGHTLY" --profile minimal \
    --component rust-src,rustc-dev,llvm-tools,rustfmt,clippy

log "cargo-oxide at ${CUDA_OXIDE_REV}"
installed_rev="$(cargo install --list 2>/dev/null | grep -o "cuda-oxide.git?rev=${CUDA_OXIDE_REV}#" || true)"
if [[ -z "$installed_rev" ]]; then
    cargo "+${CUDA_OXIDE_NIGHTLY}" install --locked --force \
        --git https://github.com/NVlabs/cuda-oxide.git --rev "$CUDA_OXIDE_REV" cargo-oxide
fi

# cargo-oxide fetches and builds its codegen backend on first use in a project
# (`cargo oxide setup` only works inside the cuda-oxide repo). Build the probe kernel
# now so a missing prerequisite fails here instead of mid-task
log "cargo oxide probe build and doctor"
KERNEL_CRATE="$REPO_ROOT/crates/speakrs-cuda-kernels"
probe_dir="$(mktemp -d)"
(cd "$KERNEL_CRATE" && CUDA_OXIDE_PTX_DIR="$probe_dir" CARGO_TARGET_DIR="$probe_dir/target" \
    cargo "+${CUDA_OXIDE_NIGHTLY}" oxide build --arch sm_75 --features probe)
test -s "$probe_dir/speakrs_cuda_kernels.ptx"
rm -rf "$probe_dir"
(cd "$KERNEL_CRATE" && cargo "+${CUDA_OXIDE_NIGHTLY}" oxide doctor)

# --- models -----------------------------------------------------------------------
HF_REVISION="$(sed -n 's/^const HF_REVISION: &str = "\([0-9a-f]\{40\}\)";$/\1/p' "$REPO_ROOT/src/models.rs")"
if [[ -z "$HF_REVISION" ]]; then
    echo "could not read HF_REVISION from $REPO_ROOT/src/models.rs" >&2
    exit 1
fi

# mirrors `catalog_assets(ExecutionMode::Cuda)` in src/models.rs: PLDA and metadata,
# then segmentation, embedding, fbank and multi-mask tail including the batched variants
MODEL_FILES=(
    plda_lda.npy plda_tr.npy plda_mu.npy plda_psi.npy plda_mean1.npy plda_mean2.npy
    wespeaker-voxceleb-resnet34.min_num_samples.txt
    segmentation-3.0.onnx segmentation-3.0-b32.onnx
    wespeaker-voxceleb-resnet34.onnx wespeaker-voxceleb-resnet34.onnx.data
    wespeaker-voxceleb-resnet34-b64.onnx
    wespeaker-fbank.onnx wespeaker-fbank-b32.onnx
    wespeaker-multimask-tail.onnx wespeaker-multimask-tail-b32.onnx
)

log "models at revision ${HF_REVISION}"
echo "$HF_REVISION" >"$WORKSPACE/models/HF_REVISION"
for file in "${MODEL_FILES[@]}"; do
    target="$WORKSPACE/models/$file"
    if [[ -s "$target" ]]; then
        continue
    fi

    # anonymous download; never pass a token from this box
    curl -fsSL --retry 3 -o "$target.part" \
        "https://huggingface.co/avencera/speakrs-models/resolve/${HF_REVISION}/${file}"
    mv "$target.part" "$target"
done

# --- record -----------------------------------------------------------------------
log "pins"
{
    echo "cuda_oxide_rev=${CUDA_OXIDE_REV}"
    echo "cuda_oxide_nightly=${CUDA_OXIDE_NIGHTLY}"
    echo "rust_stable=$(rustc +stable --version)"
    echo "rust_nightly=$(rustc "+${CUDA_OXIDE_NIGHTLY}" --version)"
    echo "llvm=$("llc-${LLVM_MAJOR}" --version | sed -n 's/.*LLVM version \(.*\)/\1/p' | head -1)"
    echo "cuda13_nvcc=$("$CUDA13_HOME/bin/nvcc" --version | sed -n 's/.*release \(.*\)/\1/p')"
    echo "hf_revision=${HF_REVISION}"
    echo "driver=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null || echo none)"
} | tee "$WORKSPACE/PINS"

df -h /
